config/routes.rb
Rails.application.routes.draw do

  get 'say/hello'
  get 'say/goodbye'
  get 'site/e2ps'
  root 'site#e2ps'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @age = 18
  end

  def goodbye

  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def e2ps

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!--this is nav-->
  <!--<div class="container-fluid">-->
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbarToggle">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h1>E2Ps</h1>
        <p>Edukasyong Pantulay Pangkabuhayan</p>
      </div>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <ul class="nav navbar-nav navbar-right nav_li">
          <li><a href="#home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#team">Our Team</a></li>
          <li><a href="#testimonial">Testimonial</a></li>
          <li><a href="#technologies">Technologies</a></li>
          <li><a href="#">Avail Scholarship</a></li>
          <li><a href="#">Tracker</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!--</div>-->
  <!--end of nav-->

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
  It is now <%= @time %>, age is <%=  @age %>
</p>
<p>
  Time to say <%= link_to "Goodbye!" , say_goodbye_path %>
</p>